イベント会場を「株式会社インプレス」に更新
Frank-kaname/ichiyasaGitSample pull request #1
Opened 2023-03-25 14:34 UTC by Frank-kaname

#変更内容
イベント開催会場を「株式会社インプレイス」に更新しました。

###拝啓
1. 「株式会社インプレイス」さんが提供してくれることになった
 1. 値下げになった
 2.

2023-03-26 14:24 UTC, ASU-Kaname commented
修正OK、マージOK

2023-03-26 14:40 UTC, ASU-Kaname requested changes
I need your comments

2023-03-26 14:40 UTC, ASU-Kaname commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場</p>
# test テスト
### テストテスト

2023-03-26 14:40 UTC, ASU-Kaname commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場</p>
kaname **kaname**

2023-03-27 14:23 UTC, Frank-kaname commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場</p>
OK I understand

2023-03-27 14:28 UTC, ASU-Kaname approved these changes

2023-03-27 14:29 UTC, ASU-Kaname commented
😸

2023-03-27 14:40 UTC, merged